name: "reverse_experiment"

data:
    src: "src"
    trg: "trg"
    # generate data with scripts/generate_reverse_task.py
    train: "scripts/train"
    dev: "scripts/dev"
    test: "scripts/test"
    level: "word"
    lowercase: False
    max_sent_length: 25
    src_voc_min_freq: 0
    src_voc_limit: 100
    trg_voc_min_freq: 0
    trg_voc_limit: 100
    #src_vocab: "reverse_model/src_vocab.txt"
    #trg_vocab: "reverse_model/trg_vocab.txt"
    

testing:
    beam_size: 1
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.001
    learning_rate_min: 0.0002
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 10
    batch_type: "sentence"
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 1
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "reverse_model"
    overwrite: True
    shuffle: True
    use_cuda: False
    max_output_length: 30
    print_valid_sents: [0, 3, 6]
    keep_last_ckpts: 2

    reinforcement_learning:
        use_reinforcement_learning: True         # specify if reinforcement learning is being used
        method: "mrt"                         # RL-method: 'reinforce', 'mrt' or 'a2c'
        log_probabilities: False                   # log token probabilities
        topk: 20                                  # log probability of topk tokens
        hyperparameters:
            # for all methods
            temperature: 1                        # Softmax temperature parameter
            # for reinforce
            reward: "bleu"                        # reward function: 'bleu', 'scaled_bleu' or 'constant'
            baseline: "average_reward_baseline"   # baseline: 'average', 'learned' or false
            # for MRT 
            alpha: 0.005                          # mrt smoothness parameter
            samples: 5                            # mrt samples
            add_gold: False                       # add gold sequence to samples
            # for NED-A2C
            critic_learning_rate: 0.000005        # critic lr, default: same as actor lr  

model:
    initializer: "xavier"
    embed_initializer: "normal"
    embed_init_weight: 0.1
    bias_initializer: "zeros"
    init_rnn_orthogonal: False
    lstm_forget_gate: 0.
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 16
            scale: False
        hidden_size: 64
        bidirectional: True
        dropout: 0.1
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 16
            scale: False
        hidden_size: 64
        dropout: 0.1
        hidden_dropout: 0.1
        num_layers: 1
        input_feeding: True
        init_hidden: "zero"
        attention: "luong"
